###
GET http://localhost:3000/ HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/courses HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/posts/2019/06 HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/courses HTTP/1.1
content-type: application/x-www-form-urlencoded

name=course


###
POST http://localhost:3000/api/courses HTTP/1.1
content-type: application/json

{
    "name": "some name"
}

###
PUT http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json

{
    "name": "put"
}


###
DELETE http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json




// *** Genres ***

###
POST http://localhost:3000/api/genres HTTP/1.1
content-type: application/json

{
    "name": "Genre"
}


###
PUT http://localhost:3000/api/genres/5d1e4ddc6472fc06218b6954 HTTP/1.1
content-type: application/json

{
    "name": "Genre Updated"
}


###
DELETE http://localhost:3000/api/genres/5d1e4ddc6472fc06218b6954 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/genres/5d1e51eadaf3870c76fe394a HTTP/1.1
content-type: application/json