###
GET http://localhost:3000/ HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/courses HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/posts/2019/06 HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/courses HTTP/1.1
content-type: application/x-www-form-urlencoded

name=course


###
POST http://localhost:3000/api/courses HTTP/1.1
content-type: application/json

{
    "name": "some name"
}

###
PUT http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json

{
    "name": "put"
}


###
DELETE http://localhost:3000/api/courses/3 HTTP/1.1
content-type: application/json




// *** Genres ***

###
POST http://localhost:3000/api/genres HTTP/1.1
content-type: application/json

{
    "name": "Genre"
}


###
PUT http://localhost:3000/api/genres/5d1e4ddc6472fc06218b6954 HTTP/1.1
content-type: application/json

{
    "name": "Genre Updated"
}


###
DELETE http://localhost:3000/api/genres/5d1e4ddc6472fc06218b6954 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/genres/5d1e51eadaf3870c76fe394a HTTP/1.1
content-type: application/json



// *** Customers ***

###
GET http://localhost:3000/api/customers HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/customers HTTP/1.1
content-type: application/json

{
    "name": "Customer1",
    "phone": "12345",
    "isGold": false
}


###
PUT http://localhost:3000/api/customers/5d1f54a7446c0030467008a3 HTTP/1.1
content-type: application/json

{
    "name": "Customer3",
    "phone": "44444",
    "isGold": true
}


###
DELETE http://localhost:3000/api/customers/5d1e568eea1934111bf27ab5 HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/api/customers/5d1e57a9fa1a3411af5da7ee HTTP/1.1
content-type: application/json




// *** Movies ***

###
GET http://localhost:3000/api/movies HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/movies HTTP/1.1
content-type: application/json

{
    "title": "New movie",
    "numberInStock": 3,
    "dailyRentalRate": 9,
    "genreId": "5d222299f55e261b570a8160"
}


// *** Rental ***

###
GET http://localhost:3000/api/rentals HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/api/rentals HTTP/1.1
content-type: application/json

{
    "customerId": "5d22219b003c0819e8967713",
    "movieId": "5d2227f5c55a2d2486b70c2e",
    "rentalFree": 10
    
}




// *** User ***

###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Dimask",
    "email": "dpol@gmail.com",
    "password": "something"
}